# Generated by Django 4.2.1 on 2023-06-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('room_name', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
